/-
Copyright (c) 2025 Xiao Tan. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: Xiao Tan and Robert Joseph George

-/

/-!
In this file, we basically have two things: formal lean codes and comments.
Lean codes are just what they are called and comments are lines of natural
language encompassed in /- -/

Though to write a lean program only requires those lean codes, sometimes it
is helpful to explain them in natural language. In fact, this file is written
as it is a book, where most lines are comments with relatively less
lean codes.

Besides, `/-! -/` is used for `markdown` display, i.e., we can have
headers(#), citations(>), etc.
And `/-- -/` is used for DocString (you will figure it out later by hovering
the cursor on some term).
Another variant of comment is `--` followed by a `newline`. For example
```lean
-- this is a comment.
```
-/

/-!
# Functional Programming in Lean

The core of modern computer proof assistants is type theory (λ-calculus),
i.e. functional programming. This chapter is intended to introduce some
basics about functional programming in `lean`. In (dependent) type
theory, we give a lot of **rules** to determine valid judgements `term: type`.
Functions are just a special rule to form a certain type, and proofs are
just the judgement `proof: proposition`, as is the Curry-Howard
correspondence. This chapter will show you (some of) those rules, and you
will learn more of them gradually later in the following chapters.
You will find that programming languages based on type theory have only a
few core features (axioms in meta language). All you need for logic can be
built from scratch within these features.
-/

/-!
## Enumerated Types

Our first example is to define a `finite` type. Just like defining a finite
set, you can define a type by enumerating all possible members.
The `keyword` to define a type is `inductive`. (You can tell why it is
called `inductive` if you have learned some type theory; otherwise,
just accept that as a name.)

The following says we are going to define a new type `Day` with members
`sunday: Day`, `monday: Day`, etc. You may think of this as
`sunday, monady, ... ∈ Day` just like a set.
-/

inductive Day where
  | monday: Day
  | tuesday: Day
  | wednesday: Day
  | thursday -- the `: Day` can be omitted since it can be infered from the context
  | friday
  | saturday | sunday -- you can write these constructors in one line
deriving Repr -- This line is only for some technical reason, indicating you can display `Day` by its constructors

/-!
As in set theory, things we concern are approximately series of **judgements**
`e1 ∈ S1`, `e2 ∈ S2`, ... Each of them is either an allowed construstion
(axiom) or the consequence of some logical inference. In type theory, the
**judgements** are of the form `t: A`, and `inductive` is one way to extend
the **judgement rules**. `:` can be considered as the relation on
`terms` and `types` freely generated by those rules. In this case, the
relation `: Day` is freely generated by **constructors** `monday`,
`tuesday`, `wednesday`, etc.
-/

/-!
We are then able to check the newly defined type by
-/

#check Day.sunday
#eval Day.sunday

/-!
If you then run command `lake build`, you can see the following output.
```
info: ././././LeanFoundations/Logic/Basic.lean:80:0: Day.sunday : Day
info: ././././LeanFoundations/Logic/Basic.lean:81:0: Day.sunday
```
-/

/-!
## Namespaces

You may have noticed that we have actually defined `Day.sunday: Day`.
To access the term `sunday`, we have to write `Day.sunday`. This
`Day` acts as a `namespace` so that if we have another type
with the same *constructor* names, we won't fall into a name conflict.
-/

inductive Weekend: Type where
  | sunday
  | saturday
  deriving Repr

#check Weekend.sunday

/-!
If you want to use those names in a namespace directly, you can `open` it
-/

open Weekend
#check sunday

/-!
Namespaces can also be defined manually. This is helpful if you want to
define something with existing names. For example, `lean` has provided the
type `Bool` with constructors `true` and `false`. To show you how to define
it from scratch, I have to define my own `Bool` using a different name
`MyBool`, or I can use a `namespace` to avoid it.
-/

inductive MyBool where
  | true
  | false
  deriving Repr

namespace scratch

  inductive Bool where
    | true | false

  open Bool

end scratch

/-!
Another application is to define the classical logic. As you know,
Curry-Howard correspondence is only true for intuitionistic logic.
But you may want to use *law of excluded middle* since we have
the double negation monad (Glivenko's theorem) embedding classical
logic in intuitionistic logc. We can put those classical axioms in a
namespace to use them if necessary. (Lean also provides such a namespace
called `Classical`, and **`lean` is classical by default**, even if you
don't open the `Classical` namespace.)
-/
namespace classical

  axiom em: forall (p: Prop), p ∨ ¬ p

end classical

/-!
## Define functions by case analysis
Now we know how to define a type by enumerating. Then a natural way to
define a function out of an enumerated type is to define a value for each
case of it. This is known as case analysis (proof by cases).

We want to define a funciton `next_weekday : Day -> Day`. Apparently, we
want to map `Day.monday` to `Day.tuesday`, `Day.tuesday` to `Day.Wednesday`,
etc. We have to notice two things here:
1. how to define a function;
2. how to do case analysis.

In type theory, to define a function, we use the λ-abstraction. For example,
to define a quadratic function $f: \mathbb{R} \to \mathbb{R}$, we may write
$f(x) = x^2$. Here, $f$ is itself a function, which does not depend on the
name of the dummy variable $x$, e.g., $f(y)=y^2$ is the same function.
So, a better way to think of it is $f := x \mapsto x ^ 2$. The `:=` is to
emphasize this is a definition. Later, this was written as $\hat{x}.x^2$
by [Whitehead and Russell][cardone2006history], and Church chose
$\lambda x. x^2$ as the final notation. This way to define a function is
called *λ-abstraction*.

In `lean`, we also define functions in this style. Besides, you also specify
the `type` for each term. In the above example, $\mathbb{R}$ is the type of
real numbers with rules $0,1,2:\mathbb{R}$, and given $x: \mathbb{R}$,
$x^2: \mathbb{R}$. Then, $λx.x^2: \mathbb{R} \to \mathbb{R}$ is the rule to
construct a function as well as its type.

So, the `next_weekday` is some
  `λ (w: Day). if w matches monday, then tuesday; ...`
In `lean`, we write it as follows.
-/

/--
The next day in a week
-/
def next_day: Day -> Day := λ (w: Day) =>
  match w with
  | Day.sunday => Day.monday
  | Day.monday => Day.tuesday
  | .tuesday => .wednesday  -- we can omit Day.
  | .wednesday => .thursday
  | .thursday => .friday
  | .friday => .saturday
  | .saturday => .sunday


/-!
λ-abstraction is defined using `λ variable => term` unlike the usual
`λ x . M` as in many text books.
> To type the `λ` in the text editor VSCode, type `\lambda` and it will
> change that to `λ`. If you don't remember this, then hover your cursor
> over the `λ` and VSCode will tell you how to type it.

Or if you don't like non-ASCII characters, use `fun variable => term` instead.
-/

def next_day_using_func: Day -> Day := fun (w: Day) =>
  match w with
  | Day.sunday => Day.monday
  | Day.monday => Day.tuesday
  | .tuesday => .wednesday  -- we can omit Day.
  | .wednesday => .thursday
  | .thursday => .friday
  | .friday => .saturday
  | .saturday => .sunday

/-!
If you want to apply the function to some term, just type
`fun term`. For example, To test the function `next_day`,
-/

#eval (next_day Day.sunday)


/-!
### Currying

The above function is defined only for one variable. In set theory,
a function for two variables is defined as $f: A \times B \to C$. This can
also be interpreted by the exponential rule: for each $a \in A$,
$f(a)$ is a function $B \to C$, i.e., we many instead define
$f: A \to (B \to C)$. This behavior is called `currying`, which is adopted
by type theory as the definition of multi-variable functions.

If we make the conventions that $\to$ is right associative, we then simply
write it as $f: A \to B \to C$. For example, we can check whether two days
of a week are equal.
-/


def day_eq_b: Day -> Day -> Bool := fun d1 =>
  match d1 with
  | .monday => fun d2 =>
    match d2 with
    | .monday => true
    | _ => false  -- `_` is for the wildcard case, i.e., all other than `.monday`
  | .tuesday => fun d2 =>
    match d2 with
    | .tuesday => true
    | _ => false
  | .wednesday => fun d2 =>
     match d2 with
    | .wednesday => true
    | _ => false
  | .thursday => fun d2 =>
    match d2 with
    | .thursday => true
    | _ => false
  | .friday => fun d2 =>
    match d2 with
    | .friday => true
    | _ => false
  | .saturday => fun d2 =>
    match d2 with
    | .saturday => true
    | _ => false
  | .sunday => fun d2 =>
    match d2 with
    | .sunday => true
    | _ => false

#eval (day_eq_b .friday) .friday
#eval (day_eq_b .sunday) .saturday

/-! Some other examples. -/
def ABA: Day -> Bool -> Day := λ a => λ b => a
def ABB: Day -> Bool -> Bool := λ a => λ b => b

/-!
Since we define $\to$ to be right-associative, the application
should then be left-associative, so we can save parentheses.
```lean
#eval day_eq_b .friday .friday
#eval day_eq_b .sunday .saturday
```
This also suggests a simpler way to define curried functions.
(Note that `day_eq_b'` is slightly different from `day_eq_b`.)
-/

def ABA': Day -> Bool -> Day := λ a b => a
def ABB': Day -> Bool -> Bool := λ a b => b


def day_eq_b': Day -> Day -> Bool := fun d1 d2 =>
  match d1 with
  | .monday =>
    match d2 with
    | .monday => true
    | _ => false  -- `_` is for the wildcard case, i.e., all other than `.monday`
  | .tuesday =>
    match d2 with
    | .tuesday => true
    | _ => false
  | .wednesday =>
     match d2 with
    | .wednesday => true
    | _ => false
  | .thursday =>
    match d2 with
    | .thursday => true
    | _ => false
  | .friday =>
    match d2 with
    | .friday => true
    | _ => false
  | .saturday =>
    match d2 with
    | .saturday => true
    | _ => false
  | .sunday =>
    match d2 with
    | .sunday => true
    | _ => false


/-!
### Syntactic Sugar
The above might be thought as the `standard` way to define a function by
λ-abstraction. However, it may not be the most convenient way to define a
function. For example, the semantics of the above `next_day` can be
interpreted as: for every `w: Day`, we want to find a term of type `Day`
for the application `next_day w`, i.e., the following. This *sweeter*
way to write down the same thing with a different syntax is called a
**syntactic sugar**. (Note the prime `'` after the name. In `lean`, we are
unable to change a defined name.)
-/

def next_day' (w: Day): Day := match w with
  | Day.sunday => Day.monday
  | Day.monday => Day.tuesday
  | .tuesday => .wednesday  -- we can omit Day.
  | .wednesday => .thursday
  | .thursday => .friday
  | .friday => .saturday
  | .saturday => .sunday


/-!
Moreover, we have an even simpler syntax sugar for `match`.
-/
def next_day'': Day -> Day
  | Day.sunday => Day.monday
  | Day.monday => Day.tuesday
  | .tuesday => .wednesday
  | .wednesday => .thursday
  | .thursday => .friday
  | .friday => .saturday
  | .saturday => .sunday

/-!
This is especially useful when you are defining a curried function.
-/

def day_eq_b'': Day -> Day -> Bool
  | .monday, .monday => true
  | .tuesday, .tuesday => true
  | .wednesday, .wednesday => true
  | .thursday, .thursday => true
  | .friday, .friday => true
  | .sunday, .sunday => true
  | .saturday, .saturday => true
  | _, _ => false

/-!
For the builtin type `Bool`, you can also use an `if ... then ... else ...`
notation instead of matching a `true`/`false`
-/

def my_not (x: Bool): Bool := if x then false else true

#eval my_not false

/-!
You can also define the `next_day` in the namespace `Day`. This time, let's
call it `Day.next`. But to use it, you have to spell the full name:
`Day.next .Wednesday`. The good part of that is you can use `w.next` for
some `w: Day`.
-/

def Day.next: Day -> Day := next_day -- certainly, you can use your own definitions here
#eval Day.next .wednesday
#eval Day.wednesday.next



/-!
## Booleans

In Lean, booleans are built-in, but we can define our own for learning purposes.
The syntax is similar to Coq but with Lean's conventions.

Key differences:
1. Constructor syntax: Lean uses `.true` instead of `true`
2. Pattern matching: Lean uses `=>` instead of `⇒`
3. Type annotations: Lean uses `:` instead of `:`
4. Function definition: Lean uses `def` instead of `Definition`
-/

def negb (b : MyBool) : MyBool :=
  match b with
  | .true => .false
  | .false => .true

def andb (b1 b2 : MyBool) : MyBool :=
  match b1 with
  | .true => b2
  | .false => .false

def orb (b1 b2 : MyBool) : MyBool :=
  match b1 with
  | .true => .true
  | .false => b2

/-!
## Natural Numbers

In Lean, natural numbers are built-in, but we can define our own for learning.
The main difference from Coq is that Lean uses `Nat` instead of `nat` and has different syntax for constructors.

Key differences:
1. Constructor names: Lean uses `zero` and `succ` instead of `O` and `S`
2. Constructor syntax: Lean uses `.zero` instead of `O`
3. Pattern matching: Lean uses `=>` instead of `⇒`
4. Type annotations: Lean uses `:` instead of `:`
5. Function definition: Lean uses `def` instead of `Definition`
-/

inductive MyNat where
  | zero : MyNat
  | succ (n : MyNat) : MyNat
deriving Repr

def pred (n : MyNat) : MyNat :=
  match n with
  | .zero => .zero
  | .succ n' => n'

def plus (n m : MyNat) : MyNat :=
  match n with
  | .zero => m
  | .succ n' => .succ (plus n' m)

def mult (n m : MyNat) : MyNat :=
  match n with
  | .zero => .zero
  | .succ n' => plus m (mult n' m)

/-!
## Proofs

In Lean, proofs are written using tactics similar to Coq, but with different syntax.
The main differences are:
1. Lean uses `by` instead of Coq's `Proof.`
2. Lean has different tactic names and syntax
3. Lean's proof automation is more powerful

Common proof techniques in Lean:
1. `cases`: For case analysis
2. `induction`: For inductive proofs
3. `rw`: For rewriting using equalities
4. `simp`: For simplification
5. `exact`: For applying lemmas
6. `apply`: For applying lemmas with unification
7. `rfl`: For reflexivity
8. `sorry`: For admitting a proof (temporarily)

Key differences in proof style:
1. Lean proofs are often more concise
2. Lean has better proof automation
3. Lean's type checker can prove more things automatically
4. Lean has better support for proof by calculation
5. Lean has better support for proof by induction
-/

/-!
Note: In Lean, many simple proofs can be done automatically by the type checker.
For educational purposes, we show the explicit proofs here.
-/

theorem plus_zero_n (n : MyNat) : plus .zero n = n := by
  induction n with
  | zero => rfl
  | succ n' ih =>
    rw [plus]

theorem plus_succ_n (n m : MyNat) : plus (.succ n) m = .succ (plus n m) := by
  induction n with
  | zero =>
    rw [plus]
    rfl
  | succ n' ih =>
    rw [plus]

/-!
## Exercises

The following exercises are translated from Software Foundations.
Try to solve them yourself! Each exercise is marked with its difficulty level.

Tips for solving exercises:
1. Start by understanding the type of the function/theorem
2. Use pattern matching for function definitions
3. Use induction for proofs about natural numbers
4. Use case analysis for proofs about booleans
5. Use rewriting for proofs about equality
6. Use simplification for proofs about arithmetic
-/

/-!
### Exercise: 1 star, standard (nandb)
Define the function nandb (negated-and) that returns true if either or both of its inputs are false.

Hint: You can use pattern matching on both arguments at once using a comma.
-/

def nandb (b1 b2 : MyBool) : MyBool := sorry

/-!
### Exercise: 1 star, standard (andb3)
Define the function andb3 that returns true when all of its inputs are true, and false otherwise.

Hint: You can use pattern matching on all three arguments at once.
-/

def andb3 (b1 b2 b3 : MyBool) : MyBool := sorry

/-!
### Exercise: 1 star, standard (factorial)
Recall the standard mathematical factorial function:
       factorial(0)  =  1
       factorial(n)  =  n * factorial(n-1)     (if n>0)
Translate this into Lean.

Hint: You'll need to use pattern matching and recursion.
-/

def factorial (n : MyNat) : MyNat := sorry

/-!
### Exercise: 1 star, standard (ltb)
Define the ltb function that tests natural numbers for less-than, yielding a boolean.

Hint: You can use pattern matching on both arguments at once.
-/

def ltb (n m : MyNat) : MyBool := sorry

/-!
### Exercise: 1 star, standard (identity_fn_applied_twice)
Prove the following theorem about boolean functions.

Hint: You'll need to use case analysis on the boolean argument.
-/

theorem identity_fn_applied_twice :
  ∀ (f : MyBool → MyBool),
  (∀ (x : MyBool), f x = x) →
  ∀ (b : MyBool), f (f b) = b := by
  sorry

/-!
### Exercise: 1 star, standard (negation_fn_applied_twice)
State and prove a theorem negation_fn_applied_twice similar to the previous one but where the second hypothesis says that the function f has the property that f x = negb x.

Hint: This is similar to the previous exercise, but you'll need to use the negb function.
-/

theorem negation_fn_applied_twice :
  ∀ (f : MyBool → MyBool),
  (∀ (x : MyBool), f x = negb x) →
  ∀ (b : MyBool), f (f b) = b := by
  sorry

/-!
### Exercise: 3 stars, standard (andb_eq_orb)
Prove the following theorem.

Hint: You'll need to use case analysis on both boolean arguments.
-/

theorem andb_eq_orb :
  ∀ (b c : MyBool),
  (andb b c = orb b c) →
  b = c := by
  sorry

/-!
### Exercise: 3 stars, standard (binary)
We can generalize our unary representation of natural numbers to the more efficient binary representation by treating a binary number as a sequence of constructors B0 and B1 (representing 0s and 1s), terminated by a Z.

Hint: You'll need to use pattern matching and recursion.
-/

inductive Bin where
  | Z
  | B0 (n : Bin)
  | B1 (n : Bin)
deriving Repr

def incr (b : Bin) : Bin :=
  match b with
  | .Z => .B1 .Z
  | .B0 b' => .B1 b'
  | .B1 b' => .B0 (incr b')

def bin_to_nat (b : Bin) : MyNat :=
  match b with
  | .Z => .zero
  | .B0 b' => plus (bin_to_nat b') (bin_to_nat b')
  | .B1 b' => MyNat.succ (plus (bin_to_nat b') (bin_to_nat b'))

/-!
### Exercise: 2 stars, standard (plus_comm)
Prove that addition is commutative.

Hint: You'll need to use induction on one of the arguments.
-/

theorem plus_comm (n m : MyNat) : plus n m = plus m n := by
  sorry

/-!
### Exercise: 2 stars, standard (plus_assoc)
Prove that addition is associative.

Hint: You'll need to use induction on one of the arguments.
-/

theorem plus_assoc (n m p : MyNat) : plus (plus n m) p = plus n (plus m p) := by
  sorry

/-!
### Exercise: 2 stars, standard (mult_comm)
Prove that multiplication is commutative.

Hint: You'll need to use induction and the plus_comm theorem.
-/

theorem mult_comm (n m : MyNat) : mult n m = mult m n := by
  sorry

/-!
## Testing Your Solutions

Each exercise comes with test cases that you can use to verify your solutions.
For example, for the nandb function:

Example test_nandb1: (nandb .true .false) = .true := by
  sorry

Example test_nandb2: (nandb .false .false) = .true := by
  sorry

Example test_nandb3: (nandb .false .true) = .true := by
  sorry

Example test_nandb4: (nandb .true .true) = .false := by
  sorry

Try to prove these test cases after implementing the functions!

Tips for testing:
1. Start with simple cases
2. Test edge cases
3. Test with different combinations of inputs
4. Use the test cases to guide your implementation
5. Make sure your implementation matches the test cases
-/
